# Generated by Django 5.1.1 on 2024-10-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_inspector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "related_model",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_models",
                        to="test_inspector.relatedmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnotherRelatedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_field", models.CharField(max_length=255)),
                (
                    "inspector_middleware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="another_related_models",
                        to="test_inspector.inspectormiddlewaremodel",
                    ),
                ),
                (
                    "related_models",
                    models.ManyToManyField(
                        related_name="many_to_many_related",
                        to="test_inspector.relatedmodel",
                    ),
                ),
            ],
        ),
    ]
