name: CI - Query-Sheriff

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger publish on version tags
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        django-version: ['3.2', '5.1']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Skip Python 3.1
        id: skip-check
        run: |
          if [[ "$(python --version)" == *"3.1"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

      - name: Install dependencies
        if: steps.skip-check.outputs.skip != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install "django==${{ matrix.django-version }}"
          pip install -r requirements.txt
          pip install coverage codecov

      - name: Run tests with pytest
        if: steps.skip-check.outputs.skip != 'true'
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage report
        if: steps.skip-check.outputs.skip != 'true' && success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
