name: CI - Query-Sheriff

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger publish on version tags
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on:  ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
        django-version: ['3.2', '5.1']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django=="${{ matrix.django-version }}"
          pip install -r requirements.txt
          pip install coverage codecov

      - name: Run tests with pytest
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage report
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before publishing
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build

      - name: Publish to testPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          python -m twine upload --repository testpypi dist/*
